theme: jekyll-theme-minimal
title: Replication files
description: Replication files for the paper [García, G.](https://gusgarciacruz.github.io/cv), [Badillo, E.](https://ebadilloe.github.io/), Aristizábal, J. "Housing informality and labor informality in space: in search of the missing links"