theme: jekyll-theme-minimal
title: Replication files
description: Replication files for the paper García, G., Badillo, E., Aristizábal, J. "Housing informality and labor informality in space in search of the missing links"