theme: jekyll-theme-minimal
title: Replication files
description: Repository for Garcia, G., Badillo, E, Aristizabal, J. (2024). "Housing informality and labor informality in space: in search of the missing links". Applied Spatial Analysis and Policy, forthcoming