theme: jekyll-theme-minimal
title: Replication files
description: In this repository you will find the replication files for the paper Housing informality and labor informality in space, in search of the missing links